{
 "title": "GCP Compute",
 "tags": [
  "gcp",
  "compute"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_ids",
    "query": "select project_id from gcp_crm_projects"
   }
  ]
 },
 "panels": [
  {
   "title": "count gcp_compute_instances by project_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select project_id, count(*) from gcp_compute_instances group by project_id"
    }
   ]
  },
  {
   "title": "count gcp_compute_instances",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from gcp_compute_instances where project_id in (${project_ids})"
    }
   ]
  },
  {
   "title": "gcp_compute_instances",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "select * from gcp_compute_instances where project_id in (${project_ids})"
    }
   ]
  },
  {
   "title": "count gcp_compute_networks by project_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select project_id, count(*) from gcp_compute_networks group by project_id"
    }
   ]
  },
  {
   "title": "count gcp_compute_networks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from gcp_compute_networks where project_id in (${project_ids})"
    }
   ]
  },
  {
   "title": "gcp_compute_networks",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 10, "y": 7 },
   "targets": [
    {
     "rawSql": "select * from gcp_compute_networks where project_id in (${project_ids})"
    }
   ]
  },
  {
   "title": "count gcp_compute_vpn_gateways by project_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select project_id, count(*) from gcp_compute_vpn_gateways group by project_id"
    }
   ]
  },
  {
   "title": "count gcp_compute_vpn_gateways",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from gcp_compute_vpn_gateways where project_id in (${project_ids})"
    }
   ]
  },
  {
   "title": "gcp_compute_vpn_gateways",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 10, "y": 14 },
   "targets": [
    {
     "rawSql": "select * from gcp_compute_vpn_gateways where project_id in (${project_ids})"
    }
   ]
  },
  {
   "title": "count gcp_compute_addresses by project_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select project_id, count(*) from gcp_compute_addresses group by project_id"
    }
   ]
  },
  {
   "title": "count gcp_compute_addresses",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from gcp_compute_addresses where project_id in (${project_ids})"
    }
   ]
  },
  {
   "title": "gcp_compute_addresses",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 10, "y": 21 },
   "targets": [
    {
     "rawSql": "select * from gcp_compute_addresses where project_id in (${project_ids})"
    }
   ]
  },
  {
   "title": "count gcp_compute_autoscalers by project_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select project_id, count(*) from gcp_compute_autoscalers group by project_id"
    }
   ]
  },
  {
   "title": "count gcp_compute_autoscalers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from gcp_compute_autoscalers where project_id in (${project_ids})"
    }
   ]
  },
  {
   "title": "gcp_compute_autoscalers",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 10, "y": 28 },
   "targets": [
    {
     "rawSql": "select * from gcp_compute_autoscalers where project_id in (${project_ids})"
    }
   ]
  },
  {
   "title": "count gcp_compute_disks by project_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select project_id, count(*) from gcp_compute_disks group by project_id"
    }
   ]
  },
  {
   "title": "count gcp_compute_disks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from gcp_compute_disks where project_id in (${project_ids})"
    }
   ]
  },
  {
   "title": "gcp_compute_disks",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 10, "y": 35 },
   "targets": [
    {
     "rawSql": "select * from gcp_compute_disks where project_id in (${project_ids})"
    }
   ]
  }
 ]
}