{
 "title": "GCP Storage",
 "tags": [
  "gcp",
  "storage"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_ids",
    "query": "select project_id from gcp_crm_projects"
   }
  ]
 },
 "panels": [
  {
   "title": "count gcp_storage_buckets by project_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select project_id, count(*) from gcp_storage_buckets group by project_id"
    }
   ]
  },
  {
   "title": "count gcp_storage_buckets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from gcp_storage_buckets where project_id in (${project_ids})"
    }
   ]
  },
  {
   "title": "gcp_storage_buckets",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "select * from gcp_storage_buckets where project_id in (${project_ids})"
    }
   ]
  }
 ]
}