{
 "title": "AWS Route53",
 "tags": [
  "aws",
  "route53"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account_ids",
    "query": "select account_id from aws_accounts"
   },
   {
    "name": "regions",
    "query": "us-east-2,us-east-1,us-west-1,us-west-2,af-south-1,ap-east-1,ap-south-1,ap-northeast-3,ap-northeast-2,ap-southeast-1,ap-southeast-2,ap-northeast-1,ca-central-1,eu-central-1,eu-west-1,eu-west-2,eu-south-1,eu-west-3,eu-north-1,me-south-1,sa-east-1"
   }
  ]
 },
 "panels": [
  {
   "title": "count aws_route53_domains by account_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select account_id, count(*) from aws_route53_domains group by account_id"
    }
   ]
  },
  {
   "title": "count aws_route53_domains",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from aws_route53_domains where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  },
  {
   "title": "count aws_route53_domains by region",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select region, count(*) from aws_route53_domains where account_id in (${account_ids}) and region in (${regions}) group by region"
    }
   ]
  },
  {
   "title": "aws_route53_domains",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "select * from aws_route53_domains where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  },
  {
   "title": "count aws_route53_hosted_zones by account_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select account_id, count(*) from aws_route53_hosted_zones group by account_id"
    }
   ]
  },
  {
   "title": "count aws_route53_hosted_zones",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from aws_route53_hosted_zones where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  },
  {
   "title": "count aws_route53_hosted_zones by region",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select region, count(*) from aws_route53_hosted_zones where account_id in (${account_ids}) and region in (${regions}) group by region"
    }
   ]
  },
  {
   "title": "aws_route53_hosted_zones",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "rawSql": "select * from aws_route53_hosted_zones where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  },
  {
   "title": "count aws_route53_trafic_policies by account_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select account_id, count(*) from aws_route53_trafic_policies group by account_id"
    }
   ]
  },
  {
   "title": "count aws_route53_trafic_policies",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from aws_route53_trafic_policies where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  },
  {
   "title": "count aws_route53_trafic_policies by region",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select region, count(*) from aws_route53_trafic_policies where account_id in (${account_ids}) and region in (${regions}) group by region"
    }
   ]
  },
  {
   "title": "aws_route53_trafic_policies",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "rawSql": "select * from aws_route53_trafic_policies where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  }
 ]
}