{
 "title": "AWS EC2",
 "tags": [
  "aws",
  "ec2"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account_ids",
    "query": "select account_id from aws_accounts"
   },
   {
    "name": "regions",
    "query": "us-east-2,us-east-1,us-west-1,us-west-2,af-south-1,ap-east-1,ap-south-1,ap-northeast-3,ap-northeast-2,ap-southeast-1,ap-southeast-2,ap-northeast-1,ca-central-1,eu-central-1,eu-west-1,eu-west-2,eu-south-1,eu-west-3,eu-north-1,me-south-1,sa-east-1"
   }
  ]
 },
 "panels": [
  {
   "title": "count aws_ec2_instances by account_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select account_id, count(*) from aws_ec2_instances group by account_id"
    }
   ]
  },
  {
   "title": "count aws_ec2_instances",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from aws_ec2_instances where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  },
  {
   "title": "count aws_ec2_instances by region",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select region, count(*) from aws_ec2_instances where account_id in (${account_ids}) and region in (${regions}) group by region"
    }
   ]
  },
  {
   "title": "aws_ec2_instances",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "select * from aws_ec2_instances where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  },
  {
   "title": "count aws_ec2_internet_gateways by account_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select account_id, count(*) from aws_ec2_internet_gateways group by account_id"
    }
   ]
  },
  {
   "title": "count aws_ec2_internet_gateways",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from aws_ec2_internet_gateways where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  },
  {
   "title": "count aws_ec2_internet_gateways by region",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select region, count(*) from aws_ec2_internet_gateways where account_id in (${account_ids}) and region in (${regions}) group by region"
    }
   ]
  },
  {
   "title": "aws_ec2_internet_gateways",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "rawSql": "select * from aws_ec2_internet_gateways where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  },
  {
   "title": "count aws_ec2_nat_gateways by account_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select account_id, count(*) from aws_ec2_nat_gateways group by account_id"
    }
   ]
  },
  {
   "title": "count aws_ec2_nat_gateways",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from aws_ec2_nat_gateways where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  },
  {
   "title": "count aws_ec2_nat_gateways by region",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select region, count(*) from aws_ec2_nat_gateways where account_id in (${account_ids}) and region in (${regions}) group by region"
    }
   ]
  },
  {
   "title": "aws_ec2_nat_gateways",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "rawSql": "select * from aws_ec2_nat_gateways where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  },
  {
   "title": "count aws_ec2_subnets by account_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select account_id, count(*) from aws_ec2_subnets group by account_id"
    }
   ]
  },
  {
   "title": "count aws_ec2_subnets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from aws_ec2_subnets where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  },
  {
   "title": "count aws_ec2_subnets by region",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select region, count(*) from aws_ec2_subnets where account_id in (${account_ids}) and region in (${regions}) group by region"
    }
   ]
  },
  {
   "title": "aws_ec2_subnets",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 21 },
   "targets": [
    {
     "rawSql": "select * from aws_ec2_subnets where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  },
  {
   "title": "count aws_ec2_vpcs by account_id",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select account_id, count(*) from aws_ec2_vpcs group by account_id"
    }
   ]
  },
  {
   "title": "count aws_ec2_vpcs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from aws_ec2_vpcs where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  },
  {
   "title": "count aws_ec2_vpcs by region",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select region, count(*) from aws_ec2_vpcs where account_id in (${account_ids}) and region in (${regions}) group by region"
    }
   ]
  },
  {
   "title": "aws_ec2_vpcs",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 28 },
   "targets": [
    {
     "rawSql": "select * from aws_ec2_vpcs where account_id in (${account_ids}) and region in (${regions})"
    }
   ]
  }
 ]
}